console.log("URI Check:", process.env.MONGODB_URI);
const mongoose = require('mongoose');
const Product = require('../models/Product');
const User = require('../models/User');
const Coupon = require('../models/Coupon');

const products = [
  { name: 'Wireless Earbuds Pro', slug: 'wireless-earbuds-pro', description: 'Premium wireless earbuds with active noise cancellation, 30hr battery life, and crystal-clear audio.', shortDescription: 'ANC earbuds with 30hr battery', brand: 'SoundWave', category: 'Electronics', price: 2499, mrp: 3999, countInStock: 45, rating: 4.5, numReviews: 234, totalSold: 1200, isFeatured: true, tags: ['earbuds', 'wireless', 'anc'], features: ['Active Noise Cancellation', '30hr battery', 'IPX5 waterproof', 'Fast charge'], images: [{ url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400', alt: 'Earbuds' }] },
  { name: 'Smart Watch Series 5', slug: 'smart-watch-series-5', description: 'Track your fitness, receive notifications and monitor health metrics with this premium smartwatch.', shortDescription: 'Health & fitness smartwatch', brand: 'TechFit', category: 'Electronics', price: 8999, mrp: 12999, countInStock: 23, rating: 4.3, numReviews: 189, totalSold: 890, isFeatured: true, tags: ['smartwatch', 'fitness', 'health'], features: ['Heart rate monitor', 'GPS', 'Sleep tracking', '7-day battery'], images: [{ url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400', alt: 'Watch' }] },
  { name: 'Running Shoes X9', slug: 'running-shoes-x9', description: 'Lightweight, responsive running shoes with superior cushioning for long-distance performance.', shortDescription: 'Lightweight performance running shoes', brand: 'SpeedRun', category: 'Footwear', price: 3499, mrp: 4999, countInStock: 67, rating: 4.7, numReviews: 456, totalSold: 2300, isFeatured: true, tags: ['shoes', 'running', 'sports'], features: ['Memory foam insole', 'Breathable mesh', 'Anti-slip sole', 'Reflective strips'], images: [{ url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400', alt: 'Shoes' }] },
  { name: 'Organic Green Tea 100g', slug: 'organic-green-tea-100g', description: 'Premium Darjeeling first flush organic green tea. Rich in antioxidants and naturally refreshing.', shortDescription: 'Premium organic Darjeeling green tea', brand: 'NatureLeaf', category: 'Groceries', price: 299, mrp: 399, countInStock: 200, rating: 4.4, numReviews: 892, totalSold: 5400, tags: ['tea', 'organic', 'health'], features: ['USDA Organic certified', 'Single estate', 'Rich in antioxidants'], images: [{ url: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400', alt: 'Green Tea' }] },
  { name: 'Yoga Mat Premium', slug: 'yoga-mat-premium', description: '6mm thick premium eco-friendly yoga mat with alignment lines and superior grip.', shortDescription: 'Eco-friendly 6mm yoga mat', brand: 'FlexZone', category: 'Sports', price: 1299, mrp: 1799, countInStock: 89, rating: 4.6, numReviews: 321, totalSold: 1800, isFeatured: true, tags: ['yoga', 'fitness', 'mat'], features: ['6mm cushioning', 'Non-slip surface', 'Eco-friendly TPE', 'Carrying strap'], images: [{ url: 'https://images.unsplash.com/photo-1601925228518-f569a1c3b0b7?w=400', alt: 'Yoga Mat' }] },
  { name: 'Noise Cancelling Headphones', slug: 'noise-cancelling-headphones', description: 'Over-ear headphones with industry-leading 40dB noise cancellation and Hi-Res audio support.', shortDescription: '40dB ANC over-ear headphones', brand: 'SoundWave', category: 'Electronics', price: 5999, mrp: 8999, countInStock: 12, rating: 4.8, numReviews: 543, totalSold: 3100, isFeatured: true, tags: ['headphones', 'anc', 'hifi'], features: ['40dB noise cancellation', 'Hi-Res audio', '25hr playback', 'Foldable design'], images: [{ url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400', alt: 'Headphones' }] },
  { name: 'Protein Powder Chocolate', slug: 'protein-powder-chocolate', description: '25g protein per serving whey concentrate with rich chocolate flavour and zero added sugar.', shortDescription: '25g protein whey concentrate', brand: 'MuscleMax', category: 'Sports', price: 1999, mrp: 2499, countInStock: 93, rating: 4.6, numReviews: 589, totalSold: 4200, tags: ['protein', 'fitness', 'supplement'], features: ['25g protein/serving', 'Zero added sugar', 'Informed Sport certified', 'Fast absorbing'], images: [{ url: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400', alt: 'Protein' }] },
  { name: 'Bluetooth Speaker', slug: 'bluetooth-speaker', description: '360° immersive sound with deep bass, 20hr playtime, waterproof body perfect for outdoor use.', shortDescription: '360° sound, 20hr waterproof speaker', brand: 'SoundWave', category: 'Electronics', price: 1899, mrp: 2499, countInStock: 78, rating: 4.4, numReviews: 298, totalSold: 2100, isFeatured: false, tags: ['speaker', 'bluetooth', 'outdoor'], features: ['360° sound', '20hr battery', 'IPX7 waterproof', 'True wireless stereo'], images: [{ url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400', alt: 'Speaker' }] },

  // Electronics
  { name: 'Mechanical Keyboard TKL', slug: 'mechanical-keyboard-tkl', description: 'Tenkeyless mechanical keyboard with Cherry MX Red switches, per-key RGB lighting, and aluminium frame for a premium typing experience.', shortDescription: 'TKL RGB mechanical keyboard', brand: 'KeyMaster', category: 'Electronics', price: 4499, mrp: 5999, countInStock: 35, rating: 4.6, numReviews: 178, totalSold: 980, isFeatured: true, tags: ['keyboard', 'mechanical', 'gaming', 'rgb'], features: ['Cherry MX Red switches', 'Per-key RGB', 'Aluminium frame', 'USB-C detachable cable'], images: [{ url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400', alt: 'Mechanical Keyboard' }] },

  { name: 'USB-C 4-Port Hub', slug: 'usb-c-4-port-hub', description: 'Compact USB-C hub with 4K HDMI, 3× USB-A, SD card reader, and 100W PD pass-through charging.', shortDescription: '7-in-1 USB-C hub with 4K HDMI', brand: 'ConnectPro', category: 'Electronics', price: 1599, mrp: 1999, countInStock: 120, rating: 4.3, numReviews: 412, totalSold: 3200, isFeatured: false, tags: ['hub', 'usb-c', 'adapter', 'laptop'], features: ['4K HDMI output', '3× USB-A 3.0', 'SD & microSD', '100W PD charging'], images: [{ url: 'https://images.unsplash.com/photo-1625895197185-efcec01cffe0?w=400', alt: 'USB-C Hub' }] },

  { name: 'Portable Power Bank 20000mAh', slug: 'portable-power-bank-20000mah', description: 'High-capacity 20000mAh power bank with 65W fast charging, dual USB-A + USB-C ports, and LED battery indicator.', shortDescription: '20000mAh 65W fast-charge power bank', brand: 'ChargeFast', category: 'Electronics', price: 2299, mrp: 2999, countInStock: 150, rating: 4.5, numReviews: 863, totalSold: 5600, isFeatured: true, tags: ['powerbank', 'charger', 'travel'], features: ['65W fast charging', 'Dual USB-A + USB-C', '20000mAh capacity', 'LED indicator'], images: [{ url: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400', alt: 'Power Bank' }] },

  { name: 'Webcam 4K Ultra HD', slug: 'webcam-4k-ultra-hd', description: 'Professional 4K webcam with autofocus, built-in stereo microphones, privacy shutter, and wide 90° field of view.', shortDescription: '4K webcam with autofocus & mic', brand: 'ClearView', category: 'Electronics', price: 6499, mrp: 8499, countInStock: 40, rating: 4.4, numReviews: 215, totalSold: 1450, isFeatured: false, tags: ['webcam', 'wfh', 'streaming', '4k'], features: ['4K 30fps', 'Autofocus', 'Stereo mic', '90° FOV', 'Privacy shutter'], images: [{ url: 'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=400', alt: 'Webcam' }] },

  { name: 'Laptop Cooling Pad', slug: 'laptop-cooling-pad', description: 'Ergonomic laptop cooling pad with 5 silent fans, adjustable height stand, and RGB lighting for laptops up to 17 inches.', shortDescription: '5-fan RGB laptop cooler', brand: 'CoolTech', category: 'Electronics', price: 999, mrp: 1499, countInStock: 200, rating: 4.2, numReviews: 534, totalSold: 4100, isFeatured: false, tags: ['laptop', 'cooling', 'accessory'], features: ['5 silent fans', 'Adjustable height', 'RGB lighting', 'Fits up to 17"'], images: [{ url: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=400', alt: 'Cooling Pad' }] },

  // Fashion & Clothing
  { name: 'Classic Oxford Shirt', slug: 'classic-oxford-shirt', description: 'Premium 100% cotton Oxford weave shirt with button-down collar and tailored fit, perfect for office or casual wear.', shortDescription: 'Premium cotton Oxford button-down shirt', brand: 'StyleHub', category: 'Clothing', price: 1299, mrp: 1899, countInStock: 180, rating: 4.4, numReviews: 302, totalSold: 2800, isFeatured: true, tags: ['shirt', 'formal', 'cotton', 'men'], features: ['100% premium cotton', 'Button-down collar', 'Tailored fit', 'Machine washable'], images: [{ url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400', alt: 'Oxford Shirt' }] },

  { name: 'High-Waist Yoga Leggings', slug: 'high-waist-yoga-leggings', description: 'Buttery-soft high-waist leggings with 4-way stretch fabric, hidden pocket, and squat-proof construction for yoga and gym.', shortDescription: 'Squat-proof high-waist leggings', brand: 'FlexZone', category: 'Clothing', price: 1099, mrp: 1599, countInStock: 240, rating: 4.7, numReviews: 671, totalSold: 6200, isFeatured: true, tags: ['leggings', 'yoga', 'women', 'gym'], features: ['4-way stretch', 'High-waist design', 'Hidden pocket', 'Squat-proof'], images: [{ url: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=400', alt: 'Yoga Leggings' }] },

  { name: 'Slim Fit Chino Pants', slug: 'slim-fit-chino-pants', description: 'Versatile slim-fit chino pants in stretch cotton blend. Available in multiple colours, ideal for smart-casual occasions.', shortDescription: 'Stretch cotton slim-fit chinos', brand: 'StyleHub', category: 'Clothing', price: 1499, mrp: 1999, countInStock: 130, rating: 4.3, numReviews: 218, totalSold: 1900, isFeatured: false, tags: ['chinos', 'pants', 'men', 'casual'], features: ['Stretch cotton blend', 'Slim fit', '4 pockets', 'Machine washable'], images: [{ url: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400', alt: 'Chino Pants' }] },

  { name: 'Oversized Graphic Hoodie', slug: 'oversized-graphic-hoodie', description: 'Super cozy 320GSM fleece oversized hoodie with bold front print, kangaroo pocket, and dropped shoulders.', shortDescription: '320GSM fleece oversized hoodie', brand: 'UrbanDrop', category: 'Clothing', price: 1799, mrp: 2299, countInStock: 95, rating: 4.5, numReviews: 387, totalSold: 3400, isFeatured: true, tags: ['hoodie', 'streetwear', 'unisex'], features: ['320GSM fleece', 'Oversized fit', 'Kangaroo pocket', 'Bold graphics'], images: [{ url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400', alt: 'Hoodie' }] },

  // Footwear
  { name: 'Leather Chelsea Boots', slug: 'leather-chelsea-boots', description: 'Handcrafted genuine leather Chelsea boots with elastic side panels, stacked heel, and durable rubber sole.', shortDescription: 'Genuine leather Chelsea boots', brand: 'SoleCraft', category: 'Footwear', price: 4999, mrp: 6999, countInStock: 52, rating: 4.6, numReviews: 198, totalSold: 1600, isFeatured: true, tags: ['boots', 'leather', 'men', 'formal'], features: ['Genuine leather upper', 'Elastic side panel', 'Stacked heel', 'Rubber sole'], images: [{ url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400', alt: 'Chelsea Boots' }] },

  { name: 'Canvas Slip-On Sneakers', slug: 'canvas-slip-on-sneakers', description: 'Lightweight canvas slip-on sneakers with memory foam insole and vulcanised rubber outsole — effortless everyday style.', shortDescription: 'Lightweight canvas slip-on sneakers', brand: 'EasyStep', category: 'Footwear', price: 799, mrp: 1199, countInStock: 310, rating: 4.2, numReviews: 944, totalSold: 8900, isFeatured: false, tags: ['sneakers', 'casual', 'unisex'], features: ['Canvas upper', 'Memory foam insole', 'Vulcanised sole', 'Slip-on design'], images: [{ url: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400', alt: 'Slip-On Sneakers' }] },

  // Home & Kitchen
  { name: 'Stainless Steel Water Bottle 1L', slug: 'stainless-steel-water-bottle-1l', description: 'Double-walled vacuum insulated stainless steel bottle keeps drinks cold 24hr / hot 12hr. BPA-free and leak-proof lid.', shortDescription: 'Vacuum insulated 1L steel bottle', brand: 'HydroLife', category: 'Home & Kitchen', price: 899, mrp: 1299, countInStock: 350, rating: 4.8, numReviews: 1204, totalSold: 11000, isFeatured: true, tags: ['bottle', 'hydration', 'eco', 'travel'], features: ['Double-wall vacuum', 'Cold 24hr / Hot 12hr', 'BPA-free', 'Leak-proof lid'], images: [{ url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400', alt: 'Water Bottle' }] },

  { name: 'Bamboo Cutting Board Set', slug: 'bamboo-cutting-board-set', description: 'Set of 3 eco-friendly bamboo cutting boards in small, medium, and large sizes with juice grooves and non-slip feet.', shortDescription: '3-piece eco bamboo cutting board set', brand: 'GreenKitchen', category: 'Home & Kitchen', price: 999, mrp: 1499, countInStock: 145, rating: 4.5, numReviews: 478, totalSold: 4300, isFeatured: false, tags: ['cutting board', 'bamboo', 'kitchen', 'eco'], features: ['Set of 3 sizes', 'Juice grooves', 'Non-slip feet', 'Eco-friendly bamboo'], images: [{ url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400', alt: 'Cutting Board' }] },

  { name: 'French Press Coffee Maker 1L', slug: 'french-press-coffee-maker-1l', description: 'Classic 1-litre borosilicate glass French press with stainless steel plunger and heat-resistant handle. Brews 8 cups.', shortDescription: '1L borosilicate glass French press', brand: 'BrewMaster', category: 'Home & Kitchen', price: 1199, mrp: 1699, countInStock: 88, rating: 4.6, numReviews: 356, totalSold: 2900, isFeatured: true, tags: ['coffee', 'french press', 'kitchen', 'brew'], features: ['1L capacity (8 cups)', 'Borosilicate glass', 'Stainless plunger', 'Heat-resistant handle'], images: [{ url: 'https://images.unsplash.com/photo-1519082274554-1ca37a3e8b0b?w=400', alt: 'French Press' }] },

  { name: 'Cast Iron Skillet 10 inch', slug: 'cast-iron-skillet-10-inch', description: 'Pre-seasoned 10-inch cast iron skillet for searing, baking, frying, and more — compatible with all cooktops including induction.', shortDescription: 'Pre-seasoned 10" cast iron skillet', brand: 'IronChef', category: 'Home & Kitchen', price: 1799, mrp: 2499, countInStock: 72, rating: 4.7, numReviews: 612, totalSold: 5100, isFeatured: true, tags: ['skillet', 'cast iron', 'cookware', 'induction'], features: ['Pre-seasoned', 'Induction compatible', 'Oven safe to 260°C', 'Lifetime durability'], images: [{ url: 'https://images.unsplash.com/photo-1575318634028-6a0cfcb60c59?w=400', alt: 'Cast Iron Skillet' }] },

  { name: 'Aroma Diffuser & Humidifier', slug: 'aroma-diffuser-humidifier', description: '500ml ultrasonic aromatherapy diffuser with 7-colour LED mood light, auto shut-off, and whisper-quiet operation.', shortDescription: '500ml ultrasonic aromatherapy diffuser', brand: 'ZenHome', category: 'Home & Kitchen', price: 1499, mrp: 1999, countInStock: 110, rating: 4.4, numReviews: 389, totalSold: 3500, isFeatured: false, tags: ['diffuser', 'aromatherapy', 'humidifier', 'home'], features: ['500ml tank', '7-colour LED', 'Auto shut-off', 'Whisper-quiet'], images: [{ url: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400', alt: 'Aroma Diffuser' }] },

  // Beauty & Personal Care
  { name: 'Vitamin C Face Serum 30ml', slug: 'vitamin-c-face-serum-30ml', description: '15% stabilised Vitamin C serum with hyaluronic acid and niacinamide for brightening, anti-ageing, and even skin tone.', shortDescription: '15% Vit C brightening face serum', brand: 'GlowLab', category: 'Beauty', price: 799, mrp: 1199, countInStock: 290, rating: 4.5, numReviews: 1034, totalSold: 9800, isFeatured: true, tags: ['serum', 'vitamin c', 'skincare', 'brightening'], features: ['15% Vitamin C', 'Hyaluronic acid', 'Niacinamide', 'Dermatologist tested'], images: [{ url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400', alt: 'Vitamin C Serum' }] },

  { name: 'Electric Face Cleanser Brush', slug: 'electric-face-cleanser-brush', description: 'Sonic face cleansing brush with 3 speed modes, soft silicone bristles, and IPX7 waterproof rating for deep-pore cleansing.', shortDescription: 'Sonic silicone face cleansing brush', brand: 'DermaPro', category: 'Beauty', price: 2499, mrp: 3499, countInStock: 65, rating: 4.3, numReviews: 267, totalSold: 2200, isFeatured: false, tags: ['face brush', 'skincare', 'cleansing'], features: ['Sonic vibration', '3 speed modes', 'Soft silicone', 'IPX7 waterproof'], images: [{ url: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400', alt: 'Face Brush' }] },

  { name: 'Sunscreen SPF 50+ PA++++ 50ml', slug: 'sunscreen-spf50-pa50ml', description: 'Lightweight, non-greasy broad-spectrum SPF 50+ PA++++ sunscreen with zinc oxide, suitable for all skin types.', shortDescription: 'Lightweight SPF 50+ broad-spectrum sunscreen', brand: 'SunShield', category: 'Beauty', price: 549, mrp: 799, countInStock: 400, rating: 4.6, numReviews: 1876, totalSold: 18000, isFeatured: true, tags: ['sunscreen', 'spf', 'skincare', 'uv protection'], features: ['SPF 50+ PA++++', 'Zinc oxide formula', 'Non-greasy', 'All skin types'], images: [{ url: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400', alt: 'Sunscreen' }] },

  // Groceries & Food
  { name: 'Cold Pressed Coconut Oil 500ml', slug: 'cold-pressed-coconut-oil-500ml', description: 'Pure cold-pressed virgin coconut oil with natural aroma, ideal for cooking, hair care, and skin moisturisation.', shortDescription: 'Virgin cold-pressed coconut oil', brand: 'PureFarm', category: 'Groceries', price: 399, mrp: 549, countInStock: 180, rating: 4.7, numReviews: 742, totalSold: 7200, isFeatured: false, tags: ['coconut oil', 'organic', 'cooking', 'haircare'], features: ['Cold-pressed', 'Virgin unrefined', 'FSSAI certified', 'Glass bottle'], images: [{ url: 'https://images.unsplash.com/photo-1611241893603-3c359704e0ee?w=400', alt: 'Coconut Oil' }] },

  { name: 'Himalayan Pink Salt 1kg', slug: 'himalayan-pink-salt-1kg', description: 'Unrefined Himalayan pink salt packed with 84+ trace minerals. Available in fine and coarse grind variants.', shortDescription: 'Unrefined Himalayan pink salt with minerals', brand: 'MountainMine', category: 'Groceries', price: 199, mrp: 299, countInStock: 500, rating: 4.5, numReviews: 1102, totalSold: 13400, isFeatured: false, tags: ['salt', 'himalayan', 'organic', 'minerals'], features: ['84+ trace minerals', 'Unrefined', 'No additives', 'Available fine & coarse'], images: [{ url: 'https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?w=400', alt: 'Himalayan Salt' }] },

  { name: 'Mixed Nuts Gift Box 500g', slug: 'mixed-nuts-gift-box-500g', description: 'Premium roasted mixed nuts — almonds, cashews, walnuts, and pistachios — lightly salted and gift-boxed.', shortDescription: 'Premium roasted mixed nuts 500g', brand: 'NutHouse', category: 'Groceries', price: 799, mrp: 999, countInStock: 220, rating: 4.8, numReviews: 543, totalSold: 4800, isFeatured: true, tags: ['nuts', 'snacks', 'gifting', 'healthy'], features: ['4 variety mix', 'Lightly salted', 'No added oil', 'Gift-ready box'], images: [{ url: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=400', alt: 'Mixed Nuts' }] },

  // Sports & Fitness
  { name: 'Adjustable Dumbbell Set 10kg', slug: 'adjustable-dumbbell-set-10kg', description: 'Space-saving adjustable dumbbell set with quick-lock mechanism, replacing 6 pairs of dumbbells in one compact unit.', shortDescription: 'Quick-lock adjustable 10kg dumbbells', brand: 'IronFit', category: 'Sports', price: 3999, mrp: 5499, countInStock: 48, rating: 4.7, numReviews: 312, totalSold: 2400, isFeatured: true, tags: ['dumbbells', 'fitness', 'gym', 'home workout'], features: ['Adjustable 2–10kg', 'Quick-lock system', 'Non-slip grip', 'Compact storage'], images: [{ url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400', alt: 'Adjustable Dumbbells' }] },

  { name: 'Jump Rope Speed Cable', slug: 'jump-rope-speed-cable', description: 'Professional speed jump rope with steel ball bearings, aluminium handles, and adjustable cable for HIIT and boxing training.', shortDescription: 'Pro speed jump rope for HIIT training', brand: 'SpeedRun', category: 'Sports', price: 549, mrp: 799, countInStock: 320, rating: 4.5, numReviews: 887, totalSold: 7600, isFeatured: false, tags: ['jump rope', 'hiit', 'cardio', 'boxing'], features: ['Steel cable', 'Ball-bearing handles', 'Adjustable length', 'Aluminium handles'], images: [{ url: 'https://images.unsplash.com/photo-1601422407692-ec4eeec1d9b3?w=400', alt: 'Jump Rope' }] },

  { name: 'Resistance Bands Set (5 pcs)', slug: 'resistance-bands-set-5pcs', description: 'Set of 5 fabric-latex resistance bands with varying resistance levels from 5lbs to 50lbs — ideal for glutes, legs and upper body.', shortDescription: '5-piece resistance band set 5–50lbs', brand: 'FlexZone', category: 'Sports', price: 699, mrp: 999, countInStock: 275, rating: 4.6, numReviews: 1025, totalSold: 9300, isFeatured: true, tags: ['resistance bands', 'fitness', 'gym', 'glutes'], features: ['5 resistance levels', 'Fabric-latex blend', 'Anti-roll design', 'Carry bag included'], images: [{ url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400', alt: 'Resistance Bands' }] },

  // Books
  { name: 'Atomic Habits — James Clear', slug: 'atomic-habits-james-clear', description: 'The #1 New York Times bestseller on how tiny changes can deliver remarkable results. A practical guide to building good habits.', shortDescription: 'Bestseller habit-building guide', brand: 'Penguin Random House', category: 'Books', price: 499, mrp: 699, countInStock: 500, rating: 4.9, numReviews: 3420, totalSold: 28000, isFeatured: true, tags: ['book', 'self-help', 'habits', 'productivity'], features: ['Paperback edition', '319 pages', 'Includes framework & exercises', 'Bestseller worldwide'], images: [{ url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400', alt: 'Atomic Habits Book' }] },

  { name: 'Deep Work — Cal Newport', slug: 'deep-work-cal-newport', description: 'A compelling case for cultivating a deep work ethic in an age of distraction. Practical rules for focused success.', shortDescription: 'Focus & productivity classic by Cal Newport', brand: 'Grand Central Publishing', category: 'Books', price: 449, mrp: 599, countInStock: 320, rating: 4.7, numReviews: 1876, totalSold: 14500, isFeatured: false, tags: ['book', 'productivity', 'focus', 'career'], features: ['Paperback', '296 pages', 'Practical strategies', 'Business bestseller'], images: [{ url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400', alt: 'Deep Work Book' }] },

  // Bags & Travel
  { name: '30L Hiking Backpack', slug: '30l-hiking-backpack', description: 'Durable 30L hiking backpack with rain cover, padded hip belt, hydration bladder sleeve, and multiple organiser pockets.', shortDescription: '30L rain-proof hiking backpack', brand: 'TrailMate', category: 'Bags', price: 2999, mrp: 3999, countInStock: 60, rating: 4.6, numReviews: 423, totalSold: 3100, isFeatured: true, tags: ['backpack', 'hiking', 'travel', 'outdoor'], features: ['30L capacity', 'Rain cover included', 'Hydration sleeve', 'Padded hip belt'], images: [{ url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400', alt: 'Hiking Backpack' }] },

  { name: 'Leather Laptop Sleeve 15 inch', slug: 'leather-laptop-sleeve-15-inch', description: 'Slim PU leather sleeve for 15-inch laptops with soft microfibre interior, magnetic closure, and accessory pocket.', shortDescription: 'Slim PU leather 15" laptop sleeve', brand: 'UrbanCarry', category: 'Bags', price: 1199, mrp: 1699, countInStock: 95, rating: 4.4, numReviews: 287, totalSold: 2300, isFeatured: false, tags: ['laptop sleeve', 'bag', 'office', 'leather'], features: ['Fits 15" laptops', 'PU leather', 'Microfibre lining', 'Magnetic closure'], images: [{ url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?w=400', alt: 'Laptop Sleeve' }] },
];

const coupons = [
  { code: 'WSKDEAL40', description: '40% off on all orders', discountType: 'percentage', discountValue: 40, minOrderAmount: 999, maxDiscountAmount: 500, validUntil: new Date('2026-12-31') },
  { code: 'WELCOME10', description: '10% off for new users', discountType: 'percentage', discountValue: 10, minOrderAmount: 0, validUntil: new Date('2026-12-31') },
  { code: 'FLAT100', description: '₹100 off on orders above ₹999', discountType: 'flat', discountValue: 100, minOrderAmount: 999, validUntil: new Date('2026-12-31') },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    await Product.deleteMany();
    await Coupon.deleteMany();
    await User.deleteMany({ role: { $ne: 'admin' } });

    await Product.insertMany(products.map(p => ({ ...p, sku: 'WSK-' + Math.random().toString(36).substr(2, 9).toUpperCase() })));
    await Coupon.insertMany(coupons);

    const adminExists = await User.findOne({ role: 'admin' });
    if (!adminExists) {
      await User.create({ name: 'Admin User', email: 'admin@weshopkeepers.com', password: 'Admin@123', role: 'admin', isVerified: true });
      console.log('Admin created: admin@weshopkeepers.com / Admin@123');
    }

    console.log(`Seeded: ${products.length} products, ${coupons.length} coupons`);
    process.exit(0);
  } catch (err) {
    console.error('Seeder error:', err.message);
    process.exit(1);
  }
};

seedDB();
